### ISSUE TITLE
grpc error on Windows 10

### ISSUE THREAD

**Issue by junhuang-ifast** [google-research/seed_rl#10]
hi I tried to run `./run_local.sh atari r2d2 4` in git bash on Windows 10 and got this error:

> file_path\seed_rl\grpc\grpc_cc.so is either not designed to run on Windows or it contains an roor. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f

**Comment by lespeholt** [comment]
Hi,

We would need a bit more context wrt. the error you see. In general should run on Windows as it uses Docker so the error message looks strange.

**Comment by junhuang-ifast** [comment]
I tried redoing everything, when I run:
`./run_local.sh atari r2d2 4`
I get

>  Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by lespeholt** [comment]
Closing this. I'm not very familiar with running Docker on Windows unfortunately.
