### ISSUE TITLE
run SEED_RL + R2D2 in pure inference/eval mode with one actor

### ISSUE THREAD

**Issue by turmeric-blend** [google-research/seed_rl#19]
is there a way to run seed_rl with r2d2 with only one eval actor for inference? I tried and I hit this assert error
```
assert FLAGS.num_actors > FLAGS.num_eval_actors, (
      'Total number of actors ({}) should be greater than number of actors '
      'reserved to eval ({})'.format(
          FLAGS.num_actors, FLAGS.num_eval_actors))
```

seems like currently the only way is to run 2 actors (1train, 1eval) at minimum.

**Comment by lespeholt** [comment]
It's not a mode we have implemented. If you don't have num_actors > num_eval_actors then eventually it will get stuck on:
https://github.com/google-research/seed_rl/blob/master/agents/r2d2/learner.py#L817

If you want a custom evaluation mode, it could make sense to copy the actor.py, and load an agent from that using a checkpoint similar to 
https://github.com/google-research/seed_rl/blob/master/agents/r2d2/learner.py#L644-L652
