### ISSUE TITLE
help understanding temp_grads in learner of vtrace

### ISSUE THREAD

**Issue by 1576012404** [google-research/seed_rl#21]
https://github.com/google-research/seed_rl/blob/eff7aaa7ab5843547fbf383fcc747b7a8ca67632/agents/vtrace/learner.py#L250
why use temp_grads? what does synchronization=tf.VariableSynchronization.ON_READ mean in the context? thank you very much?

**Comment by lespeholt** [comment]
This is specific to running multiple devices. The ON_READ synchronization actually causes the variables to be considered entirely independent when in a replica context of the distribution strategy. https://www.tensorflow.org/tutorials/distribute/custom_training

We introduced the temp grads to make sure variables were being kept on the accelerator which wasn't the case at least a while ago when you return the gradients from the experimental_run_v2 function. Quite possible that this could now be simplified. (It does look ugly.)
