### ISSUE TITLE
CUDA and driver requirements

### ISSUE THREAD

**Issue by sharsnik2** [google-research/seed_rl#22]
I'm trying to get the run_local.sh script to run on my computer, but I keep getting cuInit errors when trying to create the Conv2D layers (the exact error seems to change with CUDA/driver version). My franctic googling has suggested that this is due to a CUDA and/or cudNN version mismatch with Tensorflow 2.1. However, I'm confused because I'm not sure how much of the CUDA versioning is handled by docker, and how much needs to be set up on my host machine.

Could you please provide a list of the required versions of CUDA, cudNN, docker and the NVIDIA Container Toolkit and graphics driver to get the code to run properly?
I'm currently using a RTX 2070 SUPER gfx card with drivers 440.64, CUDA 10.2, cudNN 7.6.5, docker 19.03.8 and the most recent release of NVIDIA Container Toolkit.

**Comment by lespeholt** [comment]
Does it work for you run TF 2.1 on GPU outside of docker?

**Comment by sharsnik2** [comment]
It was not working outside of docker either. This helped me debug the issue which was the same as [here](https://stackoverflow.com/questions/61021287/tf-2-could-not-create-cudnn-handle-cudnn-status-internal-error).

However, the solution given in that thread is depreciated on TF2.1, so I had to modify the code as follows.

```
gpu_options = tf.compat.v1.GPUOptions(allow_growth=True)
sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(gpu_options=gpu_options))
tf.compat.v1.keras.backend.set_session(sess)
```

Adding this code to atari/r2d2_main.py right after the tf import seems to have done the trick. Thanks for the help.
