### ISSUE TITLE
Error when run https://github.com/google-research/seed_rl/blob/master/gcp/train_football_checkpoints.sh on GCP

### ISSUE THREAD

**Issue by jinyiping** [google-research/seed_rl#23]
I'd like to try https://github.com/google-research/seed_rl/blob/master/gcp/train_football_checkpoints.sh on GCP, I run the script, and the training was started, but a lot of error output:
![image](https://user-images.githubusercontent.com/2739581/81554127-d3820300-93b8-11ea-9271-0f42d8f16dda.png)

Should I change the worker type to standard_p100 to resolve the problem? Or any other steps I need to do?
Thanks.

**Comment by lespeholt** [comment]
the worker-replicas/actors don't have GPUs which is why you see the error. It's actually fine as GPUs are not needed on them.

**Comment by jinyiping** [comment]
Thanks, we already trained the model successfully on both VMs with/without GPU. Now we will try to train the model on TPU, we got error like this " RuntimeError: Error while creating shape. " How can we training the model on a TPU VM? 
Thanks.
