### ISSUE TITLE
Local cluster

### ISSUE THREAD

**Issue by vrindger** [google-research/seed_rl#24]
Hi,
Is it possible to run this on a local cluster environment? I wasn't sure if the local run was limited to a single node. 
What would be the hardware requirements? (e.g. would a GPU on the head node and CPUs on compute nodes work ok?)

**Comment by lespeholt** [comment]
Yes that should be possible. E.g. see how run_local.sh works

**Comment by vrindger** [comment]
I got it to work within a single docker container with run_local.sh. I have other nodes with GPUs set up with cuda and docker and would like to use those. 

How can I do that? For e.g., do I need to set TF_CONFIG in the dockerfile? Are there going to be containers running on the other nodes or will it remote in through the docker on the main node using ssh or tmux or something?
