### ISSUE TITLE
Learning type

### ISSUE THREAD

**Issue by vrindger** [google-research/seed_rl#25]
Hi,
Sorry, I'm new to RL lol 

Which RL algorithms are included or used in this? e.g. D4PG MPO A3C DQN....

**Comment by lespeholt** [comment]
V-trace https://arxiv.org/abs/1802.01561
R2D2 (DQN with additional tricks) https://openreview.net/pdf?id=r1lyTjAqYX
SAC https://arxiv.org/abs/1801.01290
