### ISSUE TITLE
unexpected error when running r2d2

### ISSUE THREAD

**Issue by turmeric-blend** [google-research/seed_rl#27]
after running rougly about 300M frames, I run into this error in my **_learner_**:

>  [_Derived_]  indices[0] = 100000 is not in [0, 100000)
         [[{{node StatefulPartitionedCall/PrioritizedReplay/Gather_3}}]]
         [[StatefulPartitionedCall]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[add_14/_26]] [Op:__inference_minimize_22442]
Function call stack:
minimize -> minimize -> minimize -> minimize

any ideas on how to fix?

note: I am running 2 docker instance on 1 machine (ie run run_local.sh twice), not sure if this is the cause but since its docker it should not affect things I suspect.

full error msg:
![Screenshot from 2020-05-16 13-32-27](https://user-images.githubusercontent.com/62788745/82111749-d5154780-9779-11ea-84ba-307595c5cabf.png)

**Comment by lespeholt** [comment]
Is this with standard hyper parameters?

This error is most likely because NaN's occur.

**Comment by turmeric-blend** [comment]
my hyperparams are as follows:

```
num_actors=32
replay_ratio=1.5
unroll_queue_max_size=100
stack_size=16
unroll_length=120
burn_in=40
batch_size=64
inference_batch_size=12
replay_buffer_size=100000
replay_buffer_min_size=5000
n_steps=5
discounting=0.997
learning_rate=0.00048
adam_epsilon=0.001
total_environment_frames=100000000000
update_target_every_n_step=2500
priority_exponent=0.9
importance_sampling_exponent=0.6
clip_norm=40
value_function_rescaling_epsilon=0.001
eval_epsilon=0.001
```
note that I am not using bit-packing hence I set stack_size=16 (more than 4). I am also using running a custom env.

I dont understand why the error message has 

>  indices[0] = 100000 is not in [0, 100000)

and 

> PrioritizedReplay

mentioned. Could it be that the buffer is trying to get a value from an index that does not exists?

**Comment by lespeholt** [comment]
As mentioned, errors like this often happen because you end up having nan's somewhere. Reducing clip_norm or learning_rate may help.

You can try and add a nan check on 'prob' in https://github.com/google-research/seed_rl/blob/master/common/utils.py#L290
