### ISSUE TITLE
PrioritizedReplay importance sampling weights calculation

### ISSUE THREAD

**Issue by wenkesj** [google-research/seed_rl#3]
I want to preface this issue with the fact that it may not necessarily be an issue, but an implementation detail that may not necessarily affect the results, but can help me understand the decisions that were made in the code and following implementation.

The importance sampling weights computation ([computed here](https://github.com/google-research/seed_rl/blob/master/common/utils.py#L293)) uses the normalized probabilities from the replay buffer, but does not compute the importance sampling weights normalized by the replay buffer (instead normalized by the sample size). In the original PER paper, (which may have been changed progressing from PER to Ape-X to R2D2, etc.), the index of the importance sampling weights (`i`) are the same as the sum indices for the probability (see [original PER paper](https://arxiv.org/pdf/1511.05952.pdf) Algorithm 1, lines 9-10). 

For my understanding, and others viewing the code, what is the correct way to do this (without the optimizations such as the sum-tree and segmenting)? In my implementations, I've computed the importance sampling weights from the replay buffer, as opposed to the samples, which way is more correct? Or if you compute the samples from the importance sampling weights, do you need to "correct" this by multiplying by the size of the samples instead of the replay buffer (replace `limit` with `num_samples`)?

Currently, the implementation is (1) gathering _then_ (2) computing the max. Alternatively, according to the indices from the PER paper, would be to (1) compute the max _then_ (2) gather, unless I am mistaken.

**Comment by RaphaelMarinier** [comment]
You raise a good point.

For R2D2, normalizing the probabilities using the max computed on the sampled batch is the correct thing to do, as we do in this code. By correct I mean that this is how it was done in the code used for the  [original R2D2 paper](https://openreview.net/pdf?id=r1lyTjAqYX).

I would interpret the PER paper as computing the max over the sampled batch: In algorithm 1, I think line 9 implicitly samples a minibatch of transition indices j, and therefore the \omega_j's and their max are computed on sampled indices as well.
I would also expect bad side effects from computing the max over all replay buffer transitions:

- Sensitivity to outliers: A single transition with huge TD error could drastically reduce importance weights for all other transitions, leading to a smaller effective learning rate.
- Sensitivity to replay buffer size: The statistics of the max depend on the size of the replay buffer. The effective learning rate would therefore vary with the replay buffer size.

I don't know for sure how the original implementations of PER and Ape-X were computing that max. You might want to get in touch with their authors to know for sure.

**Comment by wenkesj** [comment]
Your explanation is very helpful for my understanding of the implementation decision. Thank you!
