### ISSUE TITLE
ran into GRPC error when switch base docker image

### ISSUE THREAD

**Issue by turmeric-blend** [google-research/seed_rl#30]
I ran into this error when switching image from `FROM tensorflow/tensorflow:2.1.0-gpu-py3` to `FROM tensorflow/tensorflow:2.2.0-gpu`

![Screenshot from 2020-06-09 09-14-08](https://user-images.githubusercontent.com/62788745/84095459-f7754a80-aa31-11ea-90aa-bf37cc8b68f5.png)

**Comment by lespeholt** [comment]
I'll see if I can update the TF2 version :-)

**Comment by lespeholt** [comment]
Did you switch the grpc tf version too? i.e. compiled grpc on your own?

**Comment by turmeric-blend** [comment]
I tried but got this error at step 2

```
Step 2/14 : RUN git clone https://github.com/tensorflow/custom-op.git
 ---> Running in 911d1c79eb96
Cloning into 'custom-op'...
fatal: unable to access 'https://github.com/tensorflow/custom-op.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

The command '/bin/sh -c git clone https://github.com/tensorflow/custom-op.git' returned a non-zero code: 128
```

**Comment by turmeric-blend** [comment]
no im not sure how to compile grpc

**Comment by lespeholt** [comment]
Just to keep you updated, I'm looking into this. It appears the TF2.2.0 doesn't expose the required symbols. I'm discussing this with the TF team.

**Comment by lespeholt** [comment]
There was a bug in github.com/tensorflow/custom-op that has now been fixed. SEED is now using TF version to 2.2.0 :-)
