### ISSUE TITLE
How to run sac?

### ISSUE THREAD

**Issue by BlackDeal** [google-research/seed_rl#38]
Can you provide a tutorial on using sac algorithm？Thank you very much!

**Comment by lespeholt** [comment]
Hi,

We haven't provided any tuned baselines for SAC as we don't use it internally for either DM Lab, GFootball or Atari. If you want to use it for e.g. Atari you would need to add a sac_main.py file like this one: https://github.com/google-research/seed_rl/blob/master/atari/r2d2_main.py
