### ISSUE TITLE
Unable to Instantiate gRPC Server

### ISSUE THREAD

**Issue by hyang0129** [google-research/seed_rl#42]
I'm trying to instantiate a gRPC server to perform inferencing for a bunch of CPUs 

However, after cloning seed_rl and then switching my cd, I am unable to run the code provided in the readme. 

I receive  the following error.

NotFoundError: /content/seed_rl/grpc/python/../grpc_cc.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

This can be reproduced in a [colab notebook](https://colab.research.google.com/drive/1mRY8Zg220DIFhwsD8HgGpsr3HAY20k3q?usp=sharing).

Colab nbs use tf 2.3, or whatever the latest version is. Could that be causing the issue? 

What version are you guys using?

**Comment by lespeholt** [comment]
You run this outside of docker? The docker images will have all the necessary dependencies. If you prefer not do, see https://github.com/google-research/seed_rl/issues/11#issuecomment-671120703

**Comment by hyang0129** [comment]
Thank you for the quick reply. I will try following the instructions in the post you linked and if it works I'll post a working colab nb

**Comment by hyang0129** [comment]
Thanks again for referring me to that post. It appears that grpc needs to be built using docker first. I will look into that.

**Comment by hyang0129** [comment]
I have resolved the issue by adjusting the instructions from @zhuliwen. This a link to a colab nb that has grpc running.

https://colab.research.google.com/drive/1mRY8Zg220DIFhwsD8HgGpsr3HAY20k3q?usp=sharing.
