### ISSUE TITLE
Definition of batched changed ? 

### ISSUE THREAD

**Issue by jrabary** [google-research/seed_rl#47]
The last version of the `bind` function doesn't accept `batched` any more. According to the documentation only the `input_spec` shape matters

```
# This function is batched meaning it will be called once there are, in this
# case, 5 incoming calls.
@tf.function(input_signature=[tf.TensorSpec([5], tf.int32)])
def foo(x):
  return x + 1

server.bind(foo)
```

But it is not clear if each call should be a batch of 5 elements or only 1 elements. 

This example fails if you call it with 5 clients sending 1 element each.

**Comment by lespeholt** [comment]
This should definitely work both with one client sending a batch of 5 and multiple clients sending fewer. We dropped the batched= argument as it can be autodetected and all options should be supported. I just tested it and it seems to work. Can I see your test?
