### ISSUE TITLE
How to load a saved_model.pb file and continue training on it?

### ISSUE THREAD

**Issue by Moradnejad** [google-research/seed_rl#50]
Hi everyone,
I realize that this is not an issue, per se, but I couldn't find any documentation on this problem.

Let's say I use the following code to train a model and create a checkpoint.

    !bash train.sh football vtrace 4 '--total_environment_frames=10000 --game=11_vs_11_kaggle --reward_experiment=scoring,checkpoints --logdir=/agent/'

Now, I have three files in agent folder. 

How can I continue training by loading these files and train more frames?

**Comment by lespeholt** [comment]
If you use the same logdir directory it should resume training the agent.

**Comment by Moradnejad** [comment]
Thank you @lespeholt
