### ISSUE TITLE
Re-initialize agent in the middle of learner 

### ISSUE THREAD

**Issue by benlin1996** [google-research/seed_rl#54]
I try to do the hyperparmeter tuning and I need to compare different agents with different network. However, when I try to re-initialize an agent with different network in the learner loop, I always get the error when minimize function is executed.  Is re-initialize agent is allowed? Or is there any way to change the agent somewhere?

Thanks

**Comment by lespeholt** [comment]
An optimization step is changing the network so should surely be possible. What are you trying?

**Comment by benlin1996** [comment]
Sorry that I not explain it clearly. I mean change the agent with a different architecture (not only the update on the parameter of the network)

**Comment by lespeholt** [comment]
You could make a separate minimize of each type of agent or have if statements in minimize and/or inference. Or take down everything and initialize again. Depends on purpose.

**Comment by benlin1996** [comment]
Thanks for your help
