### ISSUE TITLE
how to analyse my GPU memory usage details

### ISSUE THREAD

**Issue by OwlWisdom** [google-research/seed_rl#55]
I really want to know the GPU's occupancy in atari --Pong game. My gpu is 1080Ti, and I want to konw the detail useage of its memory. Can anyone give me some guidance?

**Comment by brieyla1** [comment]
I personally use tools like wandb to get a detailed view of my GPU, CPU, memory, network and disk information throughout the run. 

A good rule of thumb is that TensorFlow will use around 90-100% of the GPUs memory for weights, you can check that using a quick `nvidia-smi` command in the command line.

the most detailed way for debugging memory leaks would be the [tensorflow profiler](https://www.tensorflow.org/guide/profiler). it allows you to visualize in a variety of different ways the memory usage and **a lot** of other components.

**Comment by OwlWisdom** [comment]
![data1](https://user-images.githubusercontent.com/33935590/102218864-a03cbf00-3f19-11eb-825e-c3e0502f1574.png)
![data2](https://user-images.githubusercontent.com/33935590/102218870-a2068280-3f19-11eb-9e74-de7fcaaa95fc.png)

This is my recorded data on GPU memory usage during training. the number of Batch_size does not vary linearly with GPU consumption. Can anyone help me analyse the reason for this?

**Comment by OwlWisdom** [comment]
> I personally use tools like wandb to get a detailed view of my GPU, CPU, memory, network and disk information throughout the run.
> 
> A good rule of thumb is that TensorFlow will use around 90-100% of the GPUs memory and most of it for weights, you can check that using a quick `nvidia-smi` command in the command line.
> 
> the most detailed way for debugging memory leaks would be the [tensorflow profiler](https://www.tensorflow.org/guide/profiler). it allows you to visualize in a variety of different ways the memory usage and **a lot** of other components.

Thank you ! I need to go through the tools you have presented.
