### ISSUE TITLE
Is there a testing mode in seed-rl?

### ISSUE THREAD

**Issue by Olin1461** [google-research/seed_rl#57]
I try to use seed-rl in testing mode (i.e. no update on the parameters). However, I cannot find the FLAG or code that can shift the train mode to test mode. Is there some code that I miss?

Thanks

**Comment by lespeholt** [comment]
There isn't a test mode built-in unfortunately. It can be accomplished by disabling the training in the learner or creating a standalone script with an actor that loads an agent and goes through the environment.

**Comment by Olin1461** [comment]
Thanks for the information
