### ISSUE TITLE
Problem of Running distributed version

### ISSUE THREAD

**Issue by Maxwell2017** [google-research/seed_rl#58]
@lespeholt 
Can distributed version use local server instead of GCP?Looking forward to your reply：）

**Comment by lespeholt** [comment]
Yes. The local script in the readme runs the actors and learner in separate processes.

**Comment by Crazyalltnt** [comment]
> Yes. The local script in the readme runs the actors and learner in separate processes.

Is there a document reference to deploy SEED RL on our own server instead of using GCP, README.md has no relevant information, thank you very much

**Comment by Maxwell2017** [comment]
THe same  question with Crazyalltnt.
@lespeholt

**Comment by lespeholt** [comment]
server_address can be changed here: https://github.com/google-research/seed_rl/blob/master/common/common_flags.py#L23
it can also be set to e.g. unix:/tmp/agent_grpc for using Unix domain sockets instead of the network stack.

Other than that, you see the flags applied in the docker file:
https://github.com/google-research/seed_rl/blob/master/docker/run.sh#L52

**Comment by Pranav-India** [comment]
Hi @Crazyalltnt @Maxwell2017  when you refer to local machine do you mean GPU or just a single CPU?

**Comment by Maxwell2017** [comment]
I mean local servers, not cloud servers

**Comment by Pranav-India** [comment]
Hi @Maxwell2017 ,ok thank you. do you know if I can run this SEED_RL on a single CPU?

**Comment by Maxwell2017** [comment]
@Pranav-India Sorry to reply you so late, I think it can run on cpu machine. However, the learner generally runs on gpu. If you use cpu, the distributed acceleration effect may not be achieved.

**Comment by Maxwell2017** [comment]
@Pranav-India Sorry to reply you so late, I think it can run on cpu machine. However, the learner generally runs on gpu. If you use cpu, the distributed acceleration effect may not be achieved.
