### ISSUE TITLE
Change number of environments

### ISSUE THREAD

**Issue by Zhehui-Huang** [google-research/seed_rl#6]
Hi,

I am recently doing experiments related to seed-rl, and I want to change number of environments.

Based on your article, I guess there should be a way to change number of environments.

However, looking at your code, I could not find the place, where we can change the number of environments. Could you please show this code and explain how to change the number of environments?

Thank you so much!

**Comment by lespeholt** [comment]
See the updated documentation here :-)
https://github.com/google-research/seed_rl#local-machine-training-on-a-single-level
