### ISSUE TITLE
What is the use case for the tensorflow gRPC batched functions?

### ISSUE THREAD

**Issue by trouverun** [google-research/seed_rl#61]
How are you supposed to utilize the batched functions in the tensorflow gRPC package? Is there a convenient way to access all of the batched call parameters? E.g if I batch 5 function calls where each call sends a 5x5 tensor as a parameter, can I access the batched 5x5x5 tensor? Or is it just some performance trick under the hood, and I'm missing the point entirely?

From what I can tell the function batching just allows you to delay the function execution until the specified amount of calls have been made, and then you get access only to a single parameter from the batch for each corresponding function execution.

**Comment by lespeholt** [comment]
Hi,

Let's say you have this:

```
server = grpc.Server([‘unix:/tmp/foo’])

@tf.function(input_signature=[tf.TensorSpec([5], tf.int32)])
def foo(x):
  return x + 1

server.bind(foo)

server.start()
```

and you run the following code 5 times concurrently:

```
client = grpc.Client(‘unix:/tmp/foo’)

client.foo(42)    # Returns 43
```

then `foo` will be called once, with a tensor with dimension [5], i.e. the five calls are batched into one.

**Comment by lespeholt** [comment]
So the answer to " E.g if I batch 5 function calls where each call sends a 5x5 tensor as a parameter, can I access the batched 5x5x5 tensor?" is yes. Feel free to reopen if it isn't clear :-)
