### ISSUE TITLE
TF 2.4.1 and gRPC

### ISSUE THREAD

**Issue by ideenfix** [google-research/seed_rl#63]
By when you plan to update gRPC to protobuf-3.14.0? After trying to compile gRPC with that version (basis of TF2.4) I received some errors from Bazel

Some information about my environment
OS: posix Linux 5.4.0-65-generic
Python:3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]

Errors received by Bazel
bazel-out/k8-opt/bin/grpc/service.pb.h:1315:80: error: 'EmptyDefault' is not a member of 'google::protobuf::internal::ArenaStringPtr'
   status_error_message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
                                                                                ^~~~~~~~~~~~
bazel-out/k8-opt/bin/grpc/service.pb.h: In member function 'std::string* seed_rl::CallResponse::_internal_mutable_status_error_message()':
bazel-out/k8-opt/bin/grpc/service.pb.h:1321:91: error: 'EmptyDefault' is not a member of 'google::protobuf::internal::ArenaStringPtr'
   return status_error_message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
                                                                                           ^~~~~~~~~~~~
grpc/ops/grpc.cc: In lambda function:
grpc/ops/grpc.cc:729:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int j = 0; j < batch_bounds.size(); j += work_unit_size) {
                         ~~^~~~~~~~~~~~~~~~~~~~~
grpc/ops/grpc.cc: In member function 'virtual void tensorflow::{anonymous}::CreateGrpcClientOp::Compute(tensorflow::OpKernelContext*)':
grpc/ops/grpc.cc:1115:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < method_output_signatures_list.size(); ++i) {
                     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Target //grpc:ops/grpc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 229.335s, Critical Path: 115.66s
INFO: 1153 processes: 1153 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

Attached:
Dockerfile
[Dockerfile.grpc.txt](https://github.com/google-research/seed_rl/files/6101642/Dockerfile.grpc.txt)

**Comment by ideenfix** [comment]
Succes. gRPC run with Tensorflow 2.4.1. Attached the Dockerfile. I don't know exactly whether some steps unnecessary but now it's run.
[Dockerfile.grpc241.txt](https://github.com/google-research/seed_rl/files/6292472/Dockerfile.grpc241.txt)

**Comment by brieyla1** [comment]
hey !

tensorflow custom ops will only be giving Symbol errors when the 2.X build is different, you can therefore use this docker image: 
`FROM tensorflow/tensorflow:2.4.0-custom-op-gpu-ubuntu16`

and everything should work as expected.

I have modified my WORKSPACE aswell, as I had problems with the vanilla one:
`

load("//tf:tf_configure.bzl", "tf_configure")
load("//gpu:cuda_configure.bzl", "cuda_configure")

tf_configure(name = "local_config_tf")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/ac1c5de1b36da4a1e3d72ca40b0e43f24266121a.tar.gz",
    ],
    strip_prefix = "grpc-ac1c5de1b36da4a1e3d72ca40b0e43f24266121a",
)

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.9.0",
    urls = [
        "https://github.com/protocolbuffers/protobuf/releases/download/v3.9.0/protobuf-all-3.9.0.tar.gz",
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()


http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.9.1",
    urls = [
        "https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protobuf-all-3.9.1.tar.gz",
    ],
)`

PS: don't forget to install tensorflow 2.4.1 for the testing:
`RUN pip3 install tensorflow-gpu==2.4.1`

have a good day.

**Comment by VegeWong** [comment]
For users having TF 2.4.1 and CUDA 11 dependencies and network issues accessing google-hosted repos and sources, the PR #66 may help.

**Comment by lespeholt** [comment]
I updated the repository to 2.4.1.
