### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'jpeg_archive'

### ISSUE THREAD

**Issue by Pranav-India** [google-research/seed_rl#64]
Hi @RaphaelMarinier @lespeholt  I am trying to run dmlab vtrace_main.py 
I ran the **./run_local.sh dmlab vtrace 4 4** this command
I received error below. can anyone help me with this? Thank you. 

`Cloning into 'lab'...
Checking out files: 100% (2601/2601), done.
Note: checking out '937d53eecf7b46fbfc56c62e8fc2257862b907f2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 937d53e [engine] Replace basic_string::compare with operator==
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //python/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
Analyzing: target //python/pip_package:build_pip_package (7 packages loaded, 15 targets configured)
Analyzing: target //python/pip_package:build_pip_package (7 packages loaded, 15 targets configured)
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 66af5b045d30b49a61faaf063ba5da7e47b9b393e3d64b40035f66ec1ade8f34
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "66af5b045d30b49a61faaf063ba5da7e47b9b393e3d64b40035f66ec1ade8f34"
DEBUG: Repository rules_cc instantiated at:
  /lab/WORKSPACE:11:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
Analyzing: target //python/pip_package:build_pip_package (16 packages loaded, 43 targets configured)
Analyzing: target //python/pip_package:build_pip_package (16 packages loaded, 43 targets configured)
Analyzing: target //python/pip_package:build_pip_package (24 packages loaded, 1712 targets configured)
Analyzing: target //python/pip_package:build_pip_package (24 packages loaded, 1712 targets configured)
INFO: SHA256 (https://github.com/abseil/abseil-cpp/archive/master.zip) = 1a3c554bec183fe3a57adb29c99c23e6a41acef180580e13c7ca794de127bf20
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1a3c554bec183fe3a57adb29c99c23e6a41acef180580e13c7ca794de127bf20"
DEBUG: Repository com_google_absl instantiated at:
  /lab/WORKSPACE:17:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
Analyzing: target //python/pip_package:build_pip_package (48 packages loaded, 2355 targets configured)
INFO: Repository jpeg_archive instantiated at:
  /lab/WORKSPACE:45:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from http://www.ijg.org/files/jpegsrc.v9c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730 but wanted 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122
ERROR: An error occurred during the fetch of repository 'jpeg_archive':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [http://www.ijg.org/files/jpegsrc.v9c.tar.gz] to /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/jpeg_archive/temp970209838112138022/jpegsrc.v9c.tar.gz: Checksum was 1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730 but wanted 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [http://www.ijg.org/files/jpegsrc.v9c.tar.gz] to /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/jpeg_archive/temp970209838112138022/jpegsrc.v9c.tar.gz: Checksum was 1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730 but wanted 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122
INFO: Repository libxml_archive instantiated at:
  /lab/WORKSPACE:53:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /lab/q3map2/BUILD:54:10: //q3map2:q3map2 depends on @jpeg_archive//:jpeg in repository @jpeg_archive which failed to fetch. no such package '@jpeg_archive//': java.io.IOException: Error downloading [http://www.ijg.org/files/jpegsrc.v9c.tar.gz] to /root/.cache/bazel/_bazel_root/3267a40151b19e3e3f8d4c8a3edf34ee/external/jpeg_archive/temp970209838112138022/jpegsrc.v9c.tar.gz: Checksum was 1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730 but wanted 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122
ERROR: Analysis of target '//python/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 64.273s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (48 packages loaded, 2355 targets configured)
FAILED: Build did NOT complete successfully (48 packages loaded, 2355 targets configured)
The command '/bin/bash -c NP_INC="$(python3 -c 'import numpy as np; print(np.get_include()[5:])')" &&     git clone https://github.com/deepmind/lab.git &&     cd lab &&     git checkout 937d53eecf7b46fbfc56c62e8fc2257862b907f2 &&     sed -i 's@python3.5@python3.6@g' python.BUILD &&     sed -i 's@glob(\[@glob(["'"$NP_INC"'/\*\*/*.h", @g' python.BUILD &&     sed -i 's@: \[@: ["'"$NP_INC"'", @g' python.BUILD &&     bazel build -c opt python/pip_package:build_pip_package --incompatible_remove_legacy_whole_archive=0 &&     pip3 install wheel &&     PYTHON_BIN_PATH="/usr/bin/python3" ./bazel-bin/python/pip_package/build_pip_package /tmp/dmlab_pkg &&     pip3 install /tmp/dmlab_pkg/DeepMind_Lab-*.whl --force-reinstall' returned a non-zero code: 1

`

Thank you

**Comment by Maxwell2017** [comment]
same question

**Comment by bgyoon** [comment]
It's a checksum failure. Insert a line to update the checksum:

    sed -i 's@650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122@1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730@g' WORKSPACE && \

before `bazel build -c opt python/pip_package:build_pip_package --incompatible_remove_legacy_whole_archive=0` line in `Dockerfile.dmlab`.

**Comment by lespeholt** [comment]
@bgyoon Thanks. This has now been fixed.
