### ISSUE TITLE
Does SEED ensure that there doesn't end up being a backlog of inferences in the unroll queue?

### ISSUE THREAD

**Issue by Edvard-D** [google-research/seed_rl#70]
I'm planning to train on a predetermined set of data rather than a game environment, and it's important that the unroll queue doesn't get backed up with old inferences in the event that the inferences are happening quicker than the minimization step. A worst case scenario would be where an environment is on step 1000 while the agent is being trained on step 200. I could imagine this being the case if there were too many environments, but there's no easy way to know how many is the right amount. Does SEED have some way of ensuring that this doesn't happen? I've tried looking over the codebase but haven't been able to find any definitive answer.

**Comment by lespeholt** [comment]
Yes, this queue will end up block: https://github.com/google-research/seed_rl/blob/master/agents/vtrace/learner.py#L336
