### ISSUE TITLE
Update is needed to Dockerfile.dmlab file

### ISSUE THREAD

**Issue by kimbring2** [google-research/seed_rl#71]
Hello,

I check DeepMind lab does not have python.BUILD file anymore. Therefore, we do not need the below the line in Dockerfile.dmlab file.

`
git checkout 937d53eecf7b46fbfc56c62e8fc2257862b907f2 && \
`
`
sed -i 's@python3.5@python3.6@g' python.BUILD && \
`
`
sed -i 's@glob(\[@glob(["'"$NP_INC"'/\*\*/*.h", @g' python.BUILD && \
`
`
sed -i 's@: \[@: ["'"$NP_INC"'", @g' python.BUILD && \
`
`
sed -i 's@650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122@1e9793e1c6ba66e7e0b6e5fe7fd0f9e935cc697854d5737adec54d93e5b3f730@g' WORKSPACE && \
`

I wish it will relieve your work.
Thank you

**Comment by lespeholt** [comment]
Thanks.

We use an older version so it's still around:
https://github.com/google-research/seed_rl/blob/master/docker/Dockerfile.dmlab#L54
